### ISSUE TITLE
[build] es5 dist version throws error.

### ISSUE THREAD

**Issue by pimdewit** [ciampo/macro-carousel#38]
`macro-carousel.es5.min.js` throws the following error:
`Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

**Comment by pimdewit** [comment]
False alarm, I did not check out the [demo](https://ciampo.github.io/macro-carousel/demo/es5.html).

@ciampo Perhaps we should also mention this process in the docs?

**Comment by ciampo** [comment]
It is mentioned in the [README](https://github.com/ciampo/macro-carousel#webcomponent-polyfills-suite).

Going to close the issue for now, but feel free to re-open it in case you still see errors after following the instructions
